apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      args:
      - "env"
      envFrom:
      - configMapRef:
          name: "app-properties"
    