apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    appUrl=http://my-app-service
    timeout=30
    a.b.c.d=ok
    username=lokesh
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: config-volume
      mountPath: /lokesh/data
    args:
    - "sleep"
    - "3600"
  volumes:
  - name: config-volume
    configMap:
      name: app-properties   